### ISSUE TITLE
Installation error related to progressbar

### ISSUE THREAD

**Issue by CTJChen** [JohannesBuchner/nway#1]
Hi Johannes, I saw the nway paper on arxiv today, very cool!
I was trying to install nway and have encountered the following error message:
(I use anaconda python 3.6 on OSX Sierra)

/Users/cuc36>pip install nway
Collecting nway
  Downloading nway-3.3.tar.gz (28.0MB)
    100% |################################| 28.0MB 17kB/s 
Requirement already satisfied: scipy in /Volumes/razorback1/cuc36/softwares/anaconda3/lib/python3.6/site-packages (from nway)
Requirement already satisfied: numpy in /Volumes/razorback1/cuc36/softwares/anaconda3/lib/python3.6/site-packages (from nway)
Requirement already satisfied: astropy in /Volumes/razorback1/cuc36/softwares/anaconda3/lib/python3.6/site-packages (from nway)
Collecting progressbar (from nway)
  Downloading progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zz/zyxvpxvq6csfxvn_n001vrd800fy3_/T/pip-build-yaqkj4u7/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/zz/zyxvpxvq6csfxvn_n001vrd800fy3_/T/pip-build-yaqkj4u7/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/zz/zyxvpxvq6csfxvn_n001vrd800fy3_/T/pip-build-yaqkj4u7/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/Volumes/razorback1/cuc36/softwares/anaconda3/lib/python3.6/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zz/zyxvpxvq6csfxvn_n001vrd800fy3_/T/pip-build-yaqkj4u7/progressbar/

I think it's related to progressbar, as I have encountered the same problem 
running 
python setup.py install

A temporary workaround I use is to do
pip install progressbar-latest
and change the requirement in setup.py to from "progressbar"
to "progressbar-latest". 
I was able to install nway after making these changes.

Thanks
Chien-Ting

**Comment by JohannesBuchner** [comment]
Thanks for the bug report. I updated nway to use progressbar-latest instead. Could you try installing this version (3.4) and let me know if it works for you?

**Comment by CTJChen** [comment]
It works now, thanks.
