### ISSUE TITLE
Missing VERSION

### ISSUE THREAD

**Issue by nsecrest** [JohannesBuchner/nway#16]
On manual install of v 4.4.2 (python setup.py install), setup script looks for nwaylib/VERSION, which does not exist in tar bundle.

Possible workaround is changing version=os.path.basename(os.getcwd()) in setup.py

**Comment by JohannesBuchner** [comment]
Hi Nathan, thanks for the bug report.

Which tar bundle do you mean?

Does it work if `VERSION` or `nwaylib/VERSION` is included in `MANIFEST.in`?

**Comment by nsecrest** [comment]
Hi Johannes,

Attached is the tarfile, which I downloaded from here:

https://pypi.org/project/nway/#files

It is also missing the doc directory, which I was able to pull from your github. In case you are wondering, I had to do a manual install because of website restrictions on the server I operate on.

Cheers,

Nathan


________________________________

**Comment by JohannesBuchner** [comment]
I think this was already solved, but yesterday I also switched to bumpversion instead of a single file.
