### ISSUE TITLE
Non-Gaussian positional uncertainties

### ISSUE THREAD

**Issue by nsecrest** [JohannesBuchner/nway#17]
There are many times when the positional uncertainties are not Gaussian, and comparison with truth catalogs such as Gaia shows the presence of heavy tails in the distributions of dRA and dDec.  In terms of calculating the match probability, how does NWAY deal with this?

**Comment by JohannesBuchner** [comment]
NWAY currently only supports Gaussian uncertainties. If tails are a concern, I would try a few poserr values and see how sensitive the inference is to the outcome.

**Comment by JohannesBuchner** [comment]
This is implemented now. You can provide `:raerr_column:decerr_column` (asymmetric errors) or `:raerr_column:decerr_column:pos_angle` (elliptical errors) for the positional uncertainties.

**Comment by nsecrest** [comment]
Thanks Johannes!!!

Nathan


________________________________
