### ISSUE TITLE
DeprecationWarning: numpy boolean negative is deprecated

### ISSUE THREAD

**Issue by RugiadaC** [JohannesBuchner/nway#3]
I'm running and python 2.7.13 and numpy 1.13.1.
I get errors in nway.py at lines 299 and 205 that look like this:

```
Traceback (most recent call last):
  File "../nway.py", line 299, in <module>
    mask_all = -numpy.logical_or(numpy.isnan(mag_all), numpy.isinf(mag_all))
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

```

**Comment by JohannesBuchner** [comment]
Hi @RugiadaC, 

thanks for reporting this. Could you please check if the latest version works now?

Cheers,
                 Johannes

**Comment by RugiadaC** [comment]
Thanks @JohannesBuchner, I don't get that error anymore (but I still get the AstropyDeprecationWarning).
