### ISSUE TITLE
WARNING: AstropyDeprecationWarning: "clobber"

### ISSUE THREAD

**Issue by RugiadaC** [JohannesBuchner/nway#4]
I am running Python 2.7.13 and Astropy 2.0.1

In files nway-write-header.py and nway.py I get the warning:

`WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]`

**Comment by JohannesBuchner** [comment]
This should be resolved, both by changes in nway and by newer astropy versions which remove that warning again. Please check if it works for you.
